name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.5
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: bun install
    - name: Run ESLint
      run: bun run lint
    - name: Ensure no changes
      run: git diff --exit-code

  ctest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.5
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: bun install
    - name: Install Playwright browsers
      run: bunx playwright install --with-deps
    - name: Build
      run: bun run build:publish
    - name: Run ctest
      run: bun run ctest

  # test:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup Bun
  #     uses: oven-sh/setup-bun@v2
  #     with:
  #       bun-version: latest
  #   - name: Use Node.js 18
  #     uses: actions/setup-node@v4
  #     with:
  #       # https://github.com/microsoft/playwright-mcp/issues/344
  #       node-version: '18.19'
  #   - name: Install dependencies
  #     run: bun install
  #   - name: Playwright install
  #     run: bunx playwright install --with-deps
  #   - name: Install MS Edge
  #     # MS Edge is not preinstalled on macOS runners.
  #     if: ${{ matrix.os == 'macos-latest' }}
  #     run: bunx playwright install msedge
  #   - name: Run tests
  #     run: bun run test

  # test_docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup Bun
  #     uses: oven-sh/setup-bun@v2
  #     with:
  #       bun-version: latest
  #   - name: Use Node.js 18
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '18'
  #   - name: Install dependencies
  #     run: bun install
  #   - name: Playwright install
  #     run: bunx playwright install --with-deps chromium
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Build and push
  #     uses: docker/build-push-action@v6
  #     with:
  #       tags: playwright-mcp-dev:latest
  #       cache-from: type=gha
  #       cache-to: type=gha,mode=max
  #       load: true
  #   - name: Run tests
  #     shell: bash
  #     run: |
  #       # Used for the Docker tests to share the test-results folder with the container.
  #       umask 0000
  #       bun run test -- --project=chromium-docker
  #     env:
  #       MCP_IN_DOCKER: 1

  # build_extension:
  #   strategy:
  #     fail-fast: false
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./extension
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Use Node.js 18
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '18'
  #       cache: 'npm'
  #       cache-dependency-path: extension/package-lock.json
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Build extension
  #     run: npm run build
  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: extension
  #       path: ./extension/dist
  #       retention-days: 7
